from step_cloud_schemas.cam_data import CamDataV1
from step_cloud_schemas.cdd_data import (
    Identification,
    TrafficParticipantType,
    ReferencePosition,
    PositionConfidenceEllipse,
    ReferenceAltitude,
    Heading,
    Speed,
    DriveDirection,
    VehicleLength,
    VehicleLengthConfidenceIndication,
    VehicleRole,
)
from step_cloud_schemas.cloud_events import MessageType
from step_lib.cam_message import CamMessageV1
from step_lib.com_manager import (
    MqttQoS,
    PublishTopicParams,
    SyncComManager,
    SyncComManagerParams,
)

def vehicle_to_message(vehicle) -> CamMessageV1:
    return CamMessageV1(
        message=CamDataV1(
            stationInfo=Identification(
                stationId=2802522858,
                stationType=TrafficParticipantType.PASSENGER_CAR,
            ),
            refPosition=ReferencePosition(
                latitude=25.4344459,
                longitude=51.232539899999999,
                confidence=PositionConfidenceEllipse(
                    semiMajorAxisLengthConfidence=203,
                    semiMinorAxisLengthConfidence=203,
                    semiMajorAxisOrientation=0,
                ),
            ),
            refAltitude=ReferenceAltitude(value=3401, confidence=2),
            heading=Heading(
                value=0,
                confidence=None,
            ),
            speed=Speed(value=0, confidence=None),
            driveDirection=DriveDirection.FORWARD,
            vehicleLength=VehicleLength(
                vehicleLengthValue=30,
                vehicleLengthConfidenceIndication=VehicleLengthConfidenceIndication.NO_TRAILER_PRESENT,  # pylint: disable=line-too-long
            ),
            vehicleWidth=10,
            longitudinalAcceleration=None,
            curvature=None,
            curvatureCalculationMode=None,
            yawRate=None,
            vehicleRole=VehicleRole.DEFAULT,
        )
    )

class UtcFormatter(logging.Formatter):
    """
    This class definition creates a custom logging formatter called UtcFormatter
    that inherits from Python's built-in logging.Formatter class.
    Here's what the class method does:
    converter: This class attribute sets the time conversion function to time.gmtime,
    which converts a time in seconds since the epoch to a struct_time in UTC
    (Coordinated Universal Time) zone.
    This means that any timestamps generated by this formatter will be in UTC.
    Note that this class doesn't define any instance methods, only a class attribute.
    """

    converter = time.gmtime

def create_logger() -> logging.Logger:
    logger = logging.getLogger(name=__name__)
    logger.setLevel(level=logging.DEBUG)
    channel = logging.FileHandler(
        filename="logfile.log",
        mode="w",
        encoding="utf-8",
        delay=False,
        errors=None,
    )
    channel.setLevel(level=logging.DEBUG)
    formatter = UtcFormatter(
        fmt="%(asctime)s.%(msecs)03d [%(levelname)s][pid=%(process)d][thread=%(threadName)s][module=%(module)s][function=%(funcName)s]: %(message)s",  # pylint: disable=line-too-long
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    channel.setFormatter(fmt=formatter)
    logger.addHandler(hdlr=channel)
    return logger



def create_sync_com_manager(logger: logging.Logger) -> SyncComManager:
    tls_params = TLSParameters(
        ca_certs=None,
        certfile=None,
        keyfile=None,
        cert_reqs=ssl.VerifyMode.CERT_REQUIRED,
        tls_version=ssl.PROTOCOL_TLSv1_2,
        ciphers=None,
        keyfile_password=None,
    )
    params = SyncComManagerParams(
        instance_name="step_lib_test_1",
        host="de-he-mn.mqtt.step.vodafone.com",
        port=8883,
        username="73f4f844-15c9-427b-8787-592b3c675d1d",
        password="a8d493c9-4214-4542-b8d7-ca1a137bfd73",
        timeout=10,
        keepalive=30,
        bind_address="",
        bind_port=0,
        clean_start=True,
        queue_type=None,
        max_queued_incoming_messages=60,
        max_queued_outgoing_messages=60,
        max_inflight_messages=60,
        max_concurrent_outgoing_calls=60,
        tls_context=None,
        tls_params=tls_params,
        tls_insecure=False,
        proxy=None,
        socket_options=None,
        session_expiry=0,
        receive_maximum=10,
        maximum_packet_size=4096,
        topic_alias_maximum=0,
        publish_topics_params=[
            PublishTopicParams(
                message_type=MessageType.CAM,
                header_topic="v2x/cam/264421_4",
                geohash_precision=8,
                qos=0,
            )
        ],
        cache_dir="./.cache",
        logger=logger,
        reconnect_interval=2,
        max_incoming_queue_rooms=60,
        max_outgoing_queue_rooms=60,
    )
    return SyncComManager(params=params)
